apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificategenerationclaims.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: CertificateGenerationClaim
    plural: certificategenerationclaims
    singular: certificategenerationclaim
    shortNames:
      - cgcs
      - cgc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
