---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-role-cluster
rules:
  - apiGroups: [""]
    resources: [pods, deployments]
    verbs: [create, patch]

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [certificategenerationclaims]
    verbs: [create, patch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-role-cluster
subjects:
  - kind: ServiceAccount
    name: cert-account