---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-role-cluster
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [ kopf.dev ]
    resources: [ kopfpeerings ]
    verbs: [ list, watch, patch, get ]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [ "" ]
    resources: [ events ]
    verbs: [ create ]

  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, list, watch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  - apiGroups:
      - apps
    resources:
      - '*'
    verbs:
      - create
      - patch
      - list
      - get
      - watch

  - apiGroups: [kopf.dev]
    resources: [certificategenerationclaims]
    verbs: [ create, patch, resume, list, get, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-role-cluster
subjects:
  - kind: ServiceAccount
    name: cert-account
    namespace: default